### PR TITLE
add support for superagent parser

### PR DESCRIPTION
**Pull request by cbou**
This enable support for non i18n: #9

### CODE REVIEW

**Comment by cbou** [comment]
@MatthewMueller This is my first draft for this feature.

Here is an example how it can be used:

```javascript
var xray = require('..')
	superAgentRequest = require('../lib/request.js');

xray('https://www.justiz-auktion.de/auctiondetails.php?id=74440')
	.select({
		title: '#auctionDetailsInfos h1'
	})
	.use(superAgentRequest({
		parser: function(res, done) {
		  res.text = '';
		  res.setEncoding('binary');
		  res.on('data', function(chunk) { res.text += chunk });
		  res.on('end', function() {
			  res.text = res.text;
		    done();
		  });
		}
	}))
	.run(function(err, object) {
		if (err) {
			throw err;
		}
		
		console.log(object);
	});
```

There are some problem with my PR:
1) It breaks a bit the current implementation because `opt` from the superagent driver isn't pass to `Superagent.agent()` anymore. 

2) It can be a bit handy to call each option of Superagent in `request.js` like this:
```javascript
      if (opts && opts.parser) {
        req.parse(opts.parser);
      }
```

I'm not very familiar with Superagent maybe I missed something...

**Comment by MatthewMueller** [comment]
nice! so the agent is to save any cookies that we come across, which is nice for logins and things. `driverOptions` doesn't seem to be used either.

Do we just need to be able to set `binary` to fix this issue?

**Comment by cbou** [comment]
No driverOptions is not used anymore, it was just a try I forgot to remove.

In this case the important part of the parser is `res.setEncoding('binary');`. 

The encoding type is then given to a [StringDecoder](http://nodejs.org/api/string_decoder.html).

Maybe my use case is not so common. For the moment I used a new [request driver](https://github.com/cbou/x-ray-request) base on the request/request module. It works well for me.

**Comment by Kikobeats** [comment]
Now the project have testing integration using Travis. Can you merge master and update the PR? :smile:

**Comment by lathropd** [comment]
closed as stale

**Pull request closed without merging**
