### PR TITLE
Fix array stream to account for empty arrays

### LINKED ISSUE #336: paginate + JSON issues
### Stream causes `JSON` errors on the last page being crawled.

the `paginate` method is throwing when I try to go past the last page.

the website I'm scrapping always display a "next page", and that last one is empty, without the link.

the `"json"` being passed to the `lib/promisify` function is this one:

```js
[

  {
    "id": "1121315593293041666"
  }
,]
```

It's being invalidated by the trailing comma.

### Your environment

* version of node: *v10.15.0*
* version of npm: *6.4.1* (I'm using yarn)
* version of yarn: *1.13.0*

### Steps to reproduce

I'm using `await x(url, context, [selector]).paginate(nextPageSelector)`

I've created an example reproduction: https://github.com/leonardodino/x-ray-repro-336 (it's a different use-case, but outlines the same behaviour)

There's a bit of ceremony wrapping `x-ray` to address #339 

### Expected behaviour

- Shouldn't throw.
- Shouldn't pass a invalid `JSON` string to `lib/promisify`.

### Actual behaviour

The trailing comma breaks the JSON parsing.

```
Unhandled rejection SyntaxError: Unexpected token ] in JSON at position 44
SyntaxError: Unexpected token ] in JSON at position 44
    at JSON.parse (<anonymous>)
    at /Users/leonardodino/Sites/redacted/node_modules/x-ray/lib/promisify.js:28:24
    at Readable.<anonymous> (/Users/leonardodino/Sites/redacted/node_modules/stream-to-string/index.js:18:13)
    at emitNone (events.js:106:13)
    at Readable.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
From previous event:
    at streamToPromise (/Users/leonardodino/Sites/redacted/node_modules/x-ray/lib/promisify.js:22:10)
    at Function.node.then (/Users/leonardodino/Sites/redacted/node_modules/x-ray/index.js:186:14)
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

### PR DESCRIPTION
**Pull request by leonardodino**
### Description

Revised the `stream_array` function to account for empty arrays as data inputs.
I reverted to adding commas before the item, so I can check if the comma is actually needed.

It was generating invalid JSON.

closes #336 

### Checklist

- [x] Code compiles correctly
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by PixelsCommander** [comment]
@matthewmueller Could you merge this? Looks safe and error it fices is pretty much reproducable...

**Comment by leonardodino** [comment]
@PixelsCommander, @lathropd seems to be the current maintainer.
maybe he can take a look later (:

If you need it right now, I have it published with my PRs here merged: [`@leonardodino/x-ray`](https://www.npmjs.com/package/@leonardodino/x-ray)

**Comment by PixelsCommander** [comment]
Thanks @leonardodino , saved me quite some time

**Comment by lathropd** [comment]
I'm traveling, but will push a new version with this as soon as I can.

**Pull request merged**
